root = "."
tmp_dir = "tmp"

[build]
  bin = "tmp\\main.exe"
  cmd = "go build -o tmp/main.exe ./cmd"
  delay = 1000
  include_ext = ["go", "tpl", "tmpl"]
  exclude_dir = ["assets", "vendor", "tmp"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  log = "air_errors.log"
  stop_on_error = true

[log]
  time = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true

[dev_tools]
  enabled = true

[hot_reload]
  enabled = true
  restart = true
  delay = 200
