version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./tmp:/app/tmp
    environment:
      CHOKIDAR_USEPOLLING: "true"
      TZ: "Asia/Jakarta"
    restart: always
    stdin_open: true
    tty: true

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: authnih
      MYSQL_DATABASE: fiber_auth
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: